action_key: meta
custom_actions:
  - command: wofi --show=drun
    action: down
    key: KEY_D
    modifiers:
      - primary
  - command: grimshot copy area
    action: down
    key: KEY_S
    modifiers:
      - shift
      - primary
  - command: swaylock -i /home/matthew-kosarek/Git/dracula/wallpaper/second-collection/illustrations/trees-and-mountains/dracula-mnt-282a36.png
    action: down
    key: KEY_L
    modifiers:
      - primary
  - command: pamixer -d 10
    action: down
    key: KEY_VOLUMEDOWN
    modifiers:
      []
  - command: pamixer -i 10
    action: down
    key: KEY_VOLUMEUP
    modifiers:
      []
  - command: pamixer -t
    action: down
    key: KEY_MUTE
    modifiers:
      []
  - command: brightnessctl s 100-
    action: down
    key: KEY_BRIGHTNESSDOWN
    modifiers:
      []
  - command: brightnessctl s +100
    action: down
    key: KEY_BRIGHTNESSUP
    modifiers:
      []
  - command: nwg-bar
    action: down
    key: KEY_E
    modifiers:
      - shift
      - primary
inner_gaps:
  x: 10
  y: 10
outer_gaps:
  x: 5
  y: 5
startup_apps:
  - command: nwg-panel
    restart_on_death: true
  - command: swaybg -i /home/matthew/Downloads/wp14988118-village-wallpapers-1.webp
    restart_on_death: true
  - command: swaync
  - command: systemd-run --user /usr/libexec/xdg-desktop-portal --replace
    in_systemd_scope: true
terminal: kitty
resize_jump: 50
border:
  size: 2
  color: 0xbd93f9ff
  focus_color: 0x50fa7bff
animations:
  - event: window_open
    type: fade_in
    function: linear
    duration: 0.300000012
    c1: 1.20000005
    c2: 1.83000004
    c3: 2.20000005
    c4: 2.09439516
    n1: 7.5625
    d1: 2.75
